"""initializing db

Revision ID: cbcb85233b67
Revises: 
Create Date: 2024-08-31 13:05:56.593584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbcb85233b67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('members', sa.Integer(), nullable=False),
    sa.Column('impact_stories', sa.Text(), nullable=False),
    sa.Column('events', sa.Text(), nullable=False),
    sa.Column('banner', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('food_banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('username')
    )
    op.create_table('donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('foodBank_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], name=op.f('fk_donations_donor_id_donors')),
    sa.ForeignKeyConstraint(['foodBank_id'], ['food_banks.id'], name=op.f('fk_donations_foodBank_id_food_banks')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('foodBank_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], name=op.f('fk_feedback_donor_id_donors')),
    sa.ForeignKeyConstraint(['foodBank_id'], ['food_banks.id'], name=op.f('fk_feedback_foodBank_id_food_banks')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['food_banks.id'], name=op.f('fk_messages_recipient_id_food_banks')),
    sa.ForeignKeyConstraint(['sender_id'], ['donors.id'], name=op.f('fk_messages_sender_id_donors')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('feedback')
    op.drop_table('donations')
    op.drop_table('food_banks')
    op.drop_table('donors')
    op.drop_table('communities')
    # ### end Alembic commands ###
